### ISSUE TITLE
importlib_metadata breaks TravisCI builds

### ISSUE THREAD

**Issue by Lawouach** [pytest-dev/pluggy#205]
Hi all,

I've noticed my builds started to fail because importlib_metadata couldn't not be found by pluggy:

Here is an example https://travis-ci.org/chaostoolkit-incubator/chaostoolkit-aws/jobs/529280278

```
running build_ext
Traceback (most recent call last):
  File "setup.py", line 97, in <module>
    main()
  File "setup.py", line 93, in main
    setuptools.setup(**setup_params)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/opt/python/3.6.3/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/python/3.6.3/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/opt/python/3.6.3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/travis/build/chaostoolkit-incubator/chaostoolkit-aws/.eggs/pytest_runner-4.4-py3.6.egg/ptr.py", line 190, in run
    return self.run_tests()
  File "/home/travis/build/chaostoolkit-incubator/chaostoolkit-aws/.eggs/pytest_runner-4.4-py3.6.egg/ptr.py", line 201, in run_tests
    result_code = __import__('pytest').main()
  File "/home/travis/build/chaostoolkit-incubator/chaostoolkit-aws/.eggs/pytest-4.4.1-py3.6.egg/pytest.py", line 7, in <module>
    from _pytest.assertion import register_assert_rewrite
  File "/home/travis/build/chaostoolkit-incubator/chaostoolkit-aws/.eggs/pytest-4.4.1-py3.6.egg/_pytest/assertion/__init__.py", line 12, in <module>
    from _pytest.assertion import rewrite
  File "/home/travis/build/chaostoolkit-incubator/chaostoolkit-aws/.eggs/pytest-4.4.1-py3.6.egg/_pytest/assertion/rewrite.py", line 23, in <module>
    from _pytest.assertion import util
  File "/home/travis/build/chaostoolkit-incubator/chaostoolkit-aws/.eggs/pytest-4.4.1-py3.6.egg/_pytest/assertion/util.py", line 10, in <module>
    import _pytest._code
  File "/home/travis/build/chaostoolkit-incubator/chaostoolkit-aws/.eggs/pytest-4.4.1-py3.6.egg/_pytest/_code/__init__.py", line 6, in <module>
    from .code import Code  # noqa
  File "/home/travis/build/chaostoolkit-incubator/chaostoolkit-aws/.eggs/pytest-4.4.1-py3.6.egg/_pytest/_code/code.py", line 15, in <module>
    import pluggy
  File "/home/travis/build/chaostoolkit-incubator/chaostoolkit-aws/.eggs/pluggy-0.10.0-py3.6.egg/pluggy/__init__.py", line 16, in <module>
    from .manager import PluginManager, PluginValidationError
  File "/home/travis/build/chaostoolkit-incubator/chaostoolkit-aws/.eggs/pluggy-0.10.0-py3.6.egg/pluggy/manager.py", line 6, in <module>
    import importlib_metadata
  File "/home/travis/build/chaostoolkit-incubator/chaostoolkit-aws/.eggs/importlib_metadata-0.9-py3.6.egg/importlib_metadata/__init__.py", line 20, in <module>
    __version__ = version(__name__)
  File "/home/travis/build/chaostoolkit-incubator/chaostoolkit-aws/.eggs/importlib_metadata-0.9-py3.6.egg/importlib_metadata/api.py", line 348, in version
    return distribution(package).version
  File "/home/travis/build/chaostoolkit-incubator/chaostoolkit-aws/.eggs/importlib_metadata-0.9-py3.6.egg/importlib_metadata/api.py", line 313, in distribution
    return Distribution.from_name(package)
  File "/home/travis/build/chaostoolkit-incubator/chaostoolkit-aws/.eggs/importlib_metadata-0.9-py3.6.egg/importlib_metadata/api.py", line 160, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.api.PackageNotFoundError: importlib_metadata
```

It happens on Python 3.6 and 3.7, but not on 3.5 because, on that one, pytest (which imports pluggy) remains on an older version.

But then again, I'm confused because, importlib_metadata is indeed installed first:

```
Searching for pluggy>=0.9
Reading https://pypi.python.org/simple/pluggy/
Downloading https://files.pythonhosted.org/packages/57/ba/54c93ac55084bde8f9195ed5cd04223b3c0d30d300801bf556565cb7675a/pluggy-0.10.0-py2.py3-none-any.whl#sha256=1c0b297d4d41bc9bdfbdc17991b35f9e1d2cfe8eaa4d7c118e86d705870d34c8
Best match: pluggy 0.10.0
Processing pluggy-0.10.0-py2.py3-none-any.whl
Installing pluggy-0.10.0-py2.py3-none-any.whl to /home/travis/build/chaostoolkit-incubator/chaostoolkit-aws/.eggs
writing requirements to /home/travis/build/chaostoolkit-incubator/chaostoolkit-aws/.eggs/pluggy-0.10.0-py3.6.egg/EGG-INFO/requires.txt
Installed /home/travis/build/chaostoolkit-incubator/chaostoolkit-aws/.eggs/pluggy-0.10.0-py3.6.egg
```

Bizarrely, I fail to reproduce locally. 

I'm wondering if this is something you folks have run into by any chance? Likely on my side but I fail to figure out what's different.

Thanks for any tips!

**Comment by neuronist** [comment]
I can't also produce locally but I'm getting the exact same error. I'm fixing the version to 0.9.0 for now on my `setup.py`. 

Luckily I realized this quick as my CI was working fine and on a second run 2 minutes later or something it stopped working because of this.

**Comment by Lawouach** [comment]
At least, I'm not going nuts :p

But this is still a mystery to me.

**Comment by RonnyPfannschmidt** [comment]
i see that you have a lot of eggs installed, its not clear to me whether importlib-metadata does actually support eggs

**Comment by Lawouach** [comment]
Their README states they don't indeed. I guess, in that case, I should likely open an issue there, right?

I'll pin pluggy to 0.9.0 for now unfortunately.

**Comment by Lawouach** [comment]
Probably ref this one https://gitlab.com/python-devs/importlib_metadata/issues/43

**Comment by RonnyPfannschmidt** [comment]
@asottile i bevel this makes importlib-metadata a absolutely breaking change until that's sorted out

**Comment by nicoddemus** [comment]
> @asottile i bevel this makes importlib-metadata a absolutely breaking change until that's sorted out

Hmmm indeed, this will be a problem. Let's see what @asottile has to say, otherwise I believe we need to revert #199 and make a `0.10.1` release.

**Comment by RonnyPfannschmidt** [comment]
i would like to see the metadata backed extracted into something configurable
while that is being done, there can also be a abstraction for back-end distributions that exposes the interesting details in a encapsulated manner,

**Comment by Lawouach** [comment]
So, while investigating how to get a correct set of test package depedencies to work, I'm now back to older versions of pluggy that failed with this one https://github.com/pytest-dev/pytest/issues/3753

I don't doubt, I'll get the right combo at some point.

**Comment by asottile** [comment]
yeah seems right, a shame that we still have to support eggs in 2019

**Comment by Lawouach** [comment]
Agreed. To be fair, I didn't even realise I was using them so i'm a little confused. I need to investigate.

**Comment by asottile** [comment]
I'm of the opinion we shouldn't try and support eggs, but I understand that's too much of a break for most people so we should revert this and we'll continue in the slow path indefinitely

**Comment by alex** [comment]
FWIW, on the pyca/cryptography front the reason we support `setup.py test` is because it represents a common entrypoint that Linux distros who redistribute us like.

If `setup.py test` is truly the last reason to care about `.egg` files, maybe we need to work with Linux distros to stop using that so we can kill `setup.py test`.

**Comment by asottile** [comment]
there's other ways to use pytest via `setup.py test` without using eggs, they're just a little more work (setting up a virtualenv, invoking in that, etc.) and sadly not the default

**Comment by alex** [comment]
https://github.com/pyca/cryptography/blob/master/setup.py#L71-L90 is our current `setup.py test` integration. How much extra code is it to make a virtualenv happen :-)

**Comment by Lawouach** [comment]
What is confusing to me is that I have many other projects, copycats of this one and they succeeded just fine so why did this one decided to fail today? It actually worked fine two weeks ago...

**Comment by alex** [comment]
🤷‍♂

**Comment by asottile** [comment]
It only started failing today as we released pluggy 0.10.0 which switched the internal mechanism from pkg_resources to importlib-metadata

**Comment by Lawouach** [comment]
Ha! I didn't realise you'd released today.

**Comment by asottile** [comment]
0.11.0 has been released -- sorry again for the breakage!

I'll be following up with documenting how to avoid eggs in `setup.py test` for `pytest` and perhaps even implementing egg support in importlib-metadata.

**Comment by nicoddemus** [comment]
Great, thanks @asottile for the lightning fast response!

**Comment by Lawouach** [comment]
Indeed. Thank you @asottile!

**Comment by neuronist** [comment]
Thanks @asottile !

**Comment by asottile** [comment]
#215 is the new attempt at rolling this out -- I've made sure to validate `python setup.py pytest` usage with eggs
