### ISSUE TITLE
[Bug] WinError 3 FileNotFoundError

### ISSUE THREAD

**Issue by aliwo** [pytest-dev/pluggy#237]
First, I want to thank you for creating and maintaining my No.1 Favorite Python Testing Library. (+ it's core dependency pluggy) During my usage of PyTest, I encountered a peculiar bug.

## Notice
I found that this Error doesn't occur in Pytest 4.3.1 + pluggy 0.9.0 

## My Environment
Windows 10 Pro
intel i5 cpu
Python 3.7
latest PyTest (5.2.1)
pluggy 0.13.0

## What I did
I created new project, fresh virtual envrionment, test.py file

```
# test.py
def test():
    assert True
```
1. I activated the virtual envrionment
2. pip install pytest
3. pytest

## What I was expecting
to pytest finish smoothly.

## What actually happened
```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2019.2.2\helpers\pycharm\_jb_pytest_runner.py", line 4, in <module>
    import pytest
  File "C:\Users\aliwo\PycharmProjects\choco\venv\lib\site-packages\pytest.py", line 7, in <module>
    from _pytest.assertion import register_assert_rewrite
  File "C:\Users\aliwo\PycharmProjects\choco\venv\lib\site-packages\_pytest\assertion\__init__.py", line 12, in <module>
    from _pytest.assertion import rewrite
  File "C:\Users\aliwo\PycharmProjects\choco\venv\lib\site-packages\_pytest\assertion\rewrite.py", line 23, in <module>
    from _pytest.assertion import util
  File "C:\Users\aliwo\PycharmProjects\choco\venv\lib\site-packages\_pytest\assertion\util.py", line 10, in <module>
    import _pytest._code
  File "C:\Users\aliwo\PycharmProjects\choco\venv\lib\site-packages\_pytest\_code\__init__.py", line 6, in <module>
    from .code import Code  # noqa
  File "C:\Users\aliwo\PycharmProjects\choco\venv\lib\site-packages\_pytest\_code\code.py", line 15, in <module>
    import pluggy
  File "C:\Users\aliwo\PycharmProjects\choco\venv\lib\site-packages\pluggy\__init__.py", line 16, in <module>
    from .manager import PluginManager, PluginValidationError
  File "C:\Users\aliwo\PycharmProjects\choco\venv\lib\site-packages\pluggy\manager.py", line 11, in <module>
    import importlib_metadata
  File "C:\Users\aliwo\PycharmProjects\choco\venv\lib\site-packages\importlib_metadata\__init__.py", line 547, in <module>
    __version__ = version(__name__)
  File "C:\Users\aliwo\PycharmProjects\choco\venv\lib\site-packages\importlib_metadata\__init__.py", line 509, in version
    return distribution(distribution_name).version
  File "C:\Users\aliwo\PycharmProjects\choco\venv\lib\site-packages\importlib_metadata\__init__.py", line 482, in distribution
    return Distribution.from_name(distribution_name)
  File "C:\Users\aliwo\PycharmProjects\choco\venv\lib\site-packages\importlib_metadata\__init__.py", line 183, in from_name
    dist = next(dists, None)
  File "C:\Users\aliwo\PycharmProjects\choco\venv\lib\site-packages\importlib_metadata\__init__.py", line 452, in <genexpr>
    return (item for item in root.iterdir()
  File "C:\Users\aliwo\AppData\Local\Programs\Python\Python37\lib\pathlib.py", line 1074, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [WinError 3] 'C:\\Users\\aliwo\\PycharmProjects\\choco\\ '
```

## Fix
I could fix the bug by modifing python pathlib
in pathlib.py line 1074:
```
for name in self._accessor.listdir(self): # where the exception happens
```
I changed it like below.
```
        try:
            temp = self._accessor.listdir(self)
        except:
            temp = self._accessor.listdir()
        for name in temp:
```
it worked like charm! but I know that it is not quite the fix I wanted. I wouldn't risk arbitrally modifing the python internal library.

## Fix 2
Downgrading pytest and pluggy worked like I metioned earlier.
downgrading only pytest to 4.3.1 won't work.
downgrading only pluggy to 0.9.0 won't work.
pytest 4.3.1 + pluggy 0.9.0 = Fix!

**Comment by asottile** [comment]
this looks like a bug with `importlib-metadata` (can probably reproduce with just `import importlib_metadata` since that's all that's happening in this stacktrace)

if you have a consistent reproduction. please open it [here](https://gitlab.com/python-devs/importlib_metadata)
