### ISSUE TITLE
No module named importlib_metadata when using Python 2.7.17

### ISSUE THREAD

**Issue by ArcLightSlavik** [pytest-dev/pluggy#256]
When running pytest on 2.7.17 i get:
```
Traceback (most recent call last):
  File "/opt/python-ext/bin/pytest", line 5, in <module>
    from pytest import main
  File "/opt/python-ext/lib/python2.7/site-packages/pytest.py", line 8, in <module>
    from _pytest.assertion import register_assert_rewrite
  File "/opt/python-ext/lib/python2.7/site-packages/_pytest/assertion/__init__.py", line 13, in <module>
    from _pytest.assertion import rewrite
  File "/opt/python-ext/lib/python2.7/site-packages/_pytest/assertion/rewrite.py", line 24, in <module>
    from _pytest.assertion import util
  File "/opt/python-ext/lib/python2.7/site-packages/_pytest/assertion/util.py", line 11, in <module>
    import _pytest._code
  File "/opt/python-ext/lib/python2.7/site-packages/_pytest/_code/__init__.py", line 7, in <module>
    from .code import Code  # noqa
  File "/opt/python-ext/lib/python2.7/site-packages/_pytest/_code/code.py", line 15, in <module>
    import pluggy
  File "/opt/python-ext/lib/python2.7/site-packages/pluggy/__init__.py", line 16, in <module>
    from .manager import PluginManager, PluginValidationError
  File "/opt/python-ext/lib/python2.7/site-packages/pluggy/manager.py", line 11, in <module>
    import importlib_metadata
ImportError: No module named importlib_metadata
```

Pip list output:
```
Package                       Version    
----------------------------- -----------
aniso8601                     8.0.0      
argh                          0.26.1     
atomicwrites                  1.3.0      
attrs                         19.3.0     
avro                          1.8.2      
Babel                         2.5.0      
backports.functools-lru-cache 1.6.1      
bcrypt                        3.1.7      
beautifulsoup4                4.7.1      
bitarray                      1.2.1      
booleano                      1.1a1      
cachetools                    3.1.1      
certifi                       2020.4.5.1 
cffi                          1.14.0     
chardet                       3.0.4      
click                         7.1.1      
cryptography                  2.9        
decorator                     4.4.2      
enum34                        1.1.10     
Flask                         0.11.1     
Flask-Cors                    3.0.1      
Flask-JWT                     0.3.2      
flask-restplus                0.13.0     
flask-swagger                 0.2.13     
funcsigs                      1.0.2      
functools32                   3.2.3.post2
futures                       3.3.0      
gdata                         2.0.18     
google-api-core               1.16.0     
google-auth                   1.13.1     
google-cloud-bigquery         1.17.0     
google-cloud-core             1.0.2      
google-cloud-datastore        1.7.4      
google-cloud-error-reporting  0.30.1     
google-cloud-kms              1.1.0      
google-cloud-logging          1.12.1     
google-cloud-pubsub           0.39.1     
google-cloud-storage          1.15.1     
google-resumable-media        0.5.0      
googleapis-common-protos      1.6.0      
grpc-google-iam-v1            0.11.4     
grpcio                        1.28.1     
gspread                       3.1.0      
gunicorn                      19.9.0     
hashids                       1.2.0      
httplib2                      0.11.3     
idna                          2.9        
impyla                        0.16.2     
ipaddress                     1.0.23     
itsdangerous                  1.1.0      
Jinja2                        2.11.1     
jsonschema                    3.2.0      
kerberos                      1.3.0      
MarkupSafe                    1.1.1      
marshmallow                   2.13.5     
mock                          2.0.0      
more-itertools                5.0.0      
msgpack                       0.6.1      
nose                          1.3.7      
numpy                         1.16.6     
oauth2client                  3.0.0      
oauthlib                      3.1.0      
packaging                     20.3       
pandas                        0.24.2     
paramiko                      2.4.3      
pbr                           5.4.5      
Pillow                        3.3.1      
pip                           20.0.2     
pluggy                        0.13.1     
ply                           3.11       
protobuf                      3.9.0      
py                            1.8.1      
pyarrow                       0.11.1     
pyasn1                        0.4.8      
pyasn1-modules                0.2.8      
pycparser                     2.20       
pycrypto                      2.6.1      
pyhash                        0.9.1      
PyJWT                         1.4.2      
PyNaCl                        1.3.0      
pyparsing                     2.4.7      
pyrsistent                    0.16.0     
pytest                        4.6.9      
pytest-mock                   2.0.0      
pytest-timeout                1.3.4      
python-dateutil               2.8.1      
python-json-logger            0.1.11     
python-slugify                3.0.2      
pytz                          2019.3     
PyYAML                        3.13       
requests                      2.23.0     
requests-oauthlib             0.8.0      
rsa                           4.0        
sasl                          0.2.1      
scikit-learn                  0.20.0     
scipy                         1.2.3      
setuptools                    44.1.0     
simplejson                    3.16.0     
six                           1.13.0     
smtpapi                       0.3.1      
soupsieve                     1.9.5      
sparkpost                     1.3.6      
text-unidecode                1.2        
thrift                        0.9.3      
thrift-sasl                   0.4a1      
timeout-decorator             0.4.0      
unicodecsv                    0.14.1     
urllib3                       1.25.8     
validators                    0.12.4     
wcwidth                       0.1.9      
Werkzeug                      0.16.1     
wheel                         0.34.2     
yaql                          1.1.3  
```
 
```
Pytest - 4.6.9, Python - 2.7.17 
Linux 3c9ad33af9b7 4.19.76-linuxkit #1 SMP Thu Oct 17 19:31:58 UTC 2019 x86_64 GNU/Linux
```

If i run the same code using python 3 it works well

**Comment by ArcLightSlavik** [comment]
Fixed it by using Python 2.7.16
