### ISSUE TITLE
Version 1.1.0 breaks devpi with "AttributeError: 'PluginManager' object has no attribute '_implprefix'"

### ISSUE THREAD

**Issue by jrast** [pytest-dev/pluggy#402]
I noticed that with the latest release of pluggy devpi fails in our CI pipelines:

````
$ devpi use http://pypi.<redacted>.ch/
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Gitlab-Runner\builds\QyWNUETU\0\python\lctools\venv\Scripts\devpi.exe\__main__.py", line 7, in <module>
  File "D:\Gitlab-Runner\builds\QyWNUETU\0\python\lctools\venv\Lib\site-packages\devpi\main.py", line 44, in main
    hub, method = initmain(argv)
                  ^^^^^^^^^^^^^^
  File "D:\Gitlab-Runner\builds\QyWNUETU\0\python\lctools\venv\Lib\site-packages\devpi\main.py", line 50, in initmain
    pm = get_pluginmanager()
         ^^^^^^^^^^^^^^^^^^^
  File "D:\Gitlab-Runner\builds\QyWNUETU\0\python\lctools\venv\Lib\site-packages\devpi\main.py", line 63, in get_pluginmanager
    pm._implprefix = "devpiclient_"
    ^^^^^^^^^^^^^^
AttributeError: 'PluginManager' object has no attribute '_implprefix'
````
- Installed Versions:
  - devpi-client: 6.0.4
  - devpi-common: 3.7.2
  - pluggy: 1.1.0
- Python Version 3.11

Downgrading to pluggy 1.0.0 solves the problem.

**Comment by fschulze** [comment]
I will fix it on the devpi side, the backward compatibility code causing this is from 2018.

**Comment by RonnyPfannschmidt** [comment]
Closing as downstream bug
